export const REQUESTED_POSTS = "REQUESTED_POSTS";
export const REQUESTED_POSTS_SUCCESS = "REQUESTED_POSTS_SUCCESS";
export const REQUESTED_POSTS_FAILD = "REQUESTED_POSTS_FAILD";

export const REQUESTED_USER = "REQUESTED_USER";
export const REQUESTED_USER_SUCCESS = "REQUESTED_USER_SUCCESS";
export const REQUESTED_USER_FAILD = "REQUESTED_USER_FAILD";

export const REQUESTED_COMMENTS = "REQUESTED_COMMENTS";
export const REQUESTED_COMMENTS_SUCCESS = "REQUESTED_COMMENTS_SUCCESS";
export const REQUESTED_COMMENTS_FAILD = "REQUESTED_COMMENTS_FAILD";
export const DELETE_COMMENTS = "DELETE_COMMENTS";
export const DELETE_COMMENTS_SUCCESS = "DELETE_COMMENTS_SUCCESS";
